apiVersion: v1
kind: ConfigMap
metadata:
  name: voltnexus-config
  namespace: voltnexus
data:
  SPRING_PROFILES_ACTIVE: "docker"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis-db"
  REDIS_PORT: "6379"
