apiVersion: v1
kind: ConfigMap
metadata:
    name: k6-test-script
    namespace: voltnexus
data:
    load-test.js: |
        import http from 'k6/http';
        import { check, sleep } from 'k6';

        export const options = {
            scenarios: {
                demo_load: {
                    executor: 'constant-arrival-rate',
                    rate: 50,                // 50 request mỗi giây (mức an toàn cho Minikube)
                    timeUnit: '1s',
                    duration: '2m',          // Chạy trong 2 phút để biểu đồ Grafana hiện đẹp
                    preAllocatedVUs: 10,     // Chuẩn bị sẵn 10 users
                    maxVUs: 50,              // Tối đa 50 users
                },
            },
            thresholds: {
                http_req_failed: ['rate<0.01'], 
                http_req_duration: ['p(95)<2000'], // 95% request phải phản hồi dưới 2 giây
            },
        };

        // Trong K8s, gọi trực tiếp Service Name 'gateway'
        const BASE_URL = 'http://gateway:8080'; 
        const TOKEN = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJwcm9maWxlSWQiOiI5NTQwMzllNi04OWViLTQxZjQtOGQ1NC0wMmFhMjFhYmM4N2YiLCJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3NzY0MTEyMzIsImV4cCI6MjA5MTc3MTIzMn0.Z6plQjnKcnOhcitN_E4gcnX4tOoeg15zGyyQHqUjFkQ';

        const params = {
            headers: {
                'Authorization': TOKEN,
                'Content-Type': 'application/json',
            },
        };

        export default function () {
            // Bước 1: Health Check Gateway (Duy trì để track sập hay chưa)
            http.get(`${BASE_URL}/actuator/health`);

            // Bước 2: Gọi API trả về nhiều dữ liệu nhất (search?page=0&size=20&keyword=VF2)
            // Không dùng sleep() để ép gateway phải handle liên tục
            http.get(`${BASE_URL}/vehicles/vehicle-catalog/variants/search?page=0&size=20&keyword=VF2`, params);
        }
